# Generated by Django 6.0 on 2026-02-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last name')),
                ('email', models.CharField(default='', max_length=200, unique=True, verbose_name='E-Mail')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Password')),
                ('telephone', models.CharField(default='', max_length=20, unique=True, verbose_name='Telephone number')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Description')),
                ('slots', models.PositiveIntegerField(default=0, verbose_name='Available Slots')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
                ('date_start', models.DateTimeField(verbose_name='Date of Event')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='planit.appuser', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Registered date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planit.appuser')),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_events', through='planit.EventAttendance', to='planit.appuser'),
        ),
    ]
