# Generated by Django 6.0 on 2026-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Event Location'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='telephone',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered Date'),
        ),
    ]
