# Generated by Django 6.0 on 2026-02-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0002_event_location_alter_appuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='', verbose_name='Password'),
        ),
    ]
