# Generated by Django 6.0 on 2026-02-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0003_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
