# Generated by Django 6.0 on 2026-02-11 17:13

from django.db import migrations

def populate_usernames(apps, schema_editor):
    AppUser = apps.get_model('planit', 'AppUser')
    for user in AppUser.objects.all():
        if not user.username:
            # Generate username from email
            user.username = user.email.split('@')[0]
            # If username exists, append a number
            base_username = user.username
            counter = 1
            while AppUser.objects.filter(username=user.username).exclude(id=user.id).exists():
                user.username = f"{base_username}{counter}"
                counter += 1
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0005_alter_appuser_managers_remove_appuser_name_and_more'),  # Replace with your last migration
    ]

    operations = [
        migrations.RunPython(populate_usernames),
    ]
