# Generated by Django 6.0 on 2026-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planit', '0007_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Event Finished'),
        ),
    ]
